name: aink
description: aink
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.4.0-17.2.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase: any
  firebase_core: any
  firebase_analytics: any
  firebase_performance: any
  firebase_auth: any
  google_sign_in: any
  #firebase_crashlytics: any
  #firebase_messaging: any
  #firebase_remote_config: any
  #cloud_firestore: any
  #flutterfire_ui: any

  # State manager
  stream_bloc: ^0.5.1
  flutter_bloc: ^8.1.1

  # Routing
  #go_router: any

  # Widgets
  google_fonts: ^3.0.1
  animations: ^2.0.4
  animated_text_kit: ^4.2.2
  photo_view: ^0.14.0
  font_awesome_flutter: ^10.2.1

  # Models and annotation
  meta: any
  equatable: any
  json_annotation: any
  freezed_annotation: any

  # Network
  http: ^0.13.5

  # Database
  shared_preferences: any

  # Utility
  l: any
  intl: any
  path: ^1.8.2
  url_launcher: any
  theme_tailor_annotation: any
  platform_info: any
  flutter_batteries: ^0.0.6-dev
  flutter_blurhash: ^0.7.0
  blobs: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: any
  build_web_compilers: any
  dart_code_metrics: any
  icons_launcher: ^2.0.5
  flutter_native_splash: ^2.2.9
  pubspec_generator: any
  theme_tailor: any
  json_serializable: any
  freezed: any
  flutter_gen_runner: any

#dependency_overrides:
#  analyzer: ">=4.2.0 <5.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/image/sunflower_512x512.jpg
    - assets/font/

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant/
  line_length: 120
